# Generated by Django 5.2.1 on 2025-11-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_facture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='updatedAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='detail_facture',
            name='updatedAt',
            field=models.DateTimeField(null=True),
        ),
    ]
