# Generated by Django 5.2.1 on 2025-11-01 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_facture', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='nom',
        ),
        migrations.AddField(
            model_name='facture',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facture',
            name='updatedAt',
            field=models.DateTimeField(null=True),
        ),
    ]
