# Generated by Django 5.2.1 on 2025-10-31 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_facture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(null=True)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('updatedAt', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('pu', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=6)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('updatedAt', models.DateTimeField()),
                ('appartement', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_facture.appartement')),
            ],
        ),
        migrations.CreateModel(
            name='Detail_facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('updatedAt', models.DateTimeField()),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_facture.facture')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_facture.produit')),
            ],
        ),
    ]
