# Generated by Django 5.2.1 on 2025-11-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_facture', '0002_facture_updatedat_alter_detail_facture_updatedat'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='imprimer',
            field=models.BooleanField(default=False),
        ),
    ]
