# Generated by Django 5.2.1 on 2025-10-31 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_facture', '0002_facture_produit_detail_facture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartement',
            name='updatedAt',
            field=models.DateTimeField(null=True),
        ),
    ]
