# Generated by Django 5.2.1 on 2025-10-31 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_facture', '0003_alter_appartement_updatedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='quantite',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='updatedAt',
            field=models.DateTimeField(null=True),
        ),
    ]
