# Generated by Django 5.2.1 on 2025-11-02 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_facture', '0003_facture_imprimer'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
